### ISSUE TITLE
dangerous use of internal armadillo functionality

### ISSUE THREAD

**Issue by conradsnicta** [boennecd/dynamichazard#3]
https://github.com/boennecd/dynamichazard/blob/e26e9a037c25f1f70484a945ea0765e1861ec943/src/arma_n_rcpp.h#L43

The function `arma::arma_ostream::print_elem()` is an internal Armadillo function subject to change and/or removal without notice.  Extract from Armadillo documentation on the dangers of using [internal functions](http://arma.sourceforge.net/docs.html#api_additions): 

> ***Caveat:*** any function, class, constant or other code not explicitly described in the [public API documentation](http://arma.sourceforge.net/docs.html) is considered as part of the underlying internal implementation details, and may change or be removed without notice. (In other words, don't use internal functionality).

CC: @eddelbuettel

**Comment by boennecd** [comment]
Thanks for pointing this out and sorry. It is clearly stated in the documentation that usage of internal functions should be avoided.

Are you soon going to change the `arma::arma_ostream::print_elem()` function and thus should I quickly change this and make a new commit to CRAN?

**Comment by conradsnicta** [comment]
I recommend removing all use of `arma::arma_ostream::print_elem()` from your code. I'm going to  refactor `arma_ostream` for the next release of armadillo, so all corresponding functionality is likely to change, or even disappear.
